### ISSUE TITLE
Implement Double type

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/xdpw#10]
Currently XD Pascal supports only one (32-bit) floating-point type, `Real`, which is equivalent to `Single` in Delphi. All other types, `Single`, `Double`, and `Extended`, are formally equivalent to this `Real`. Thus, the actual computation precision is always limited to 32-bit representations.

While the `Extended` type is not very practical (as it is too large and not portable to non-x87 platforms), the `Double` type could be really useful. The difficulty is that any procedure parameter or temporary value in XD Pascal is stored in a single 32-bit stack cell or register, and all function results are returned via `eax`. The introduction of the `Double` type may destroy this homogeneity.

The alternative approach is to switch to 64-bit code generation (#9) and get the `Double` type 'out-of-the-box'.

**Comment by Mazdaywik** [comment]
А закрыто почему? Сделано или лень делать?

**Comment by vtereshkov** [comment]
Done. Now XD Pascal correctly solves the [N body benchmark problem](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-fpascal-1.html) (though with rather poor performance) and [supports GetTime() in Raylib](https://github.com/vtereshkov/raylib-xdpw/commit/beaf3bf0fac11b5d07c087e4e11411137e4cd4fc).

**Comment by Mazdaywik** [comment]
Можно было в сообщение коммита 94acbc40e0ffc3fcd4f78726c640ccf77d0cd46b добавить #10 и коммит привязался бы к задаче.
