### ISSUE TITLE
does not work in delphi 10.3

### ISSUE THREAD

**Issue by ghost** [vtereshkov/xdpw#2]
does not work in delphi 10.3 community :(

**Comment by vtereshkov** [comment]
I tested it with Delphi 6/7. What is going wrong? A compile-time or a runtime error? Could you please provide more details? Did you try it with Free Pascal?

**Comment by ghost** [comment]
unicode

**Comment by ghost** [comment]
String and Char is unicode, not ansi

**Comment by vtereshkov** [comment]
Our thanks to Embarcadero for breaking up the backward compatibility.

**Comment by vtereshkov** [comment]
To build XD Pascal with Delphi 2009+, just replace (in Commom.pas):
```
  TCharacter = Char;
  PCharacter = PChar;
  TString = string;  
  TShortString = string;
```
with
```
  TCharacter = AnsiChar;
  PCharacter = PAnsiChar;
  TString = AnsiString;  
  TShortString = ShortString;
```
