### ISSUE TITLE
XD Pascal in KolibriOS

### ISSUE THREAD

**Issue by leency** [vtereshkov/xdpw#20]
Hello,

Firstly I would like to thanks a lot the author,
and notify you that XD Pascal was ported into KolibriOS, as well as some apps.

http://forum.cantorsys.com/viewtopic.php?pid=794#p794
https://maxcodehack.github.io/hll-kos/pas/xdpas/

Thanks again for a nice compiler and have a nice day!

Best Regards,
Kiril aka Leency from KolibriOS Team

**Comment by vtereshkov** [comment]
@leency Great news! Thank you!
