### ISSUE TITLE
ошибка при компиляции проекта с Delphi7

### ISSUE THREAD

**Issue by AntKrotov** [vtereshkov/xdpw#5]
файл common.inc
строка 544
`  INTEGERTYPE:    Result := -2147483648;`
целочисленное переполнение

Для Delphi надо написать
`  INTEGERTYPE:    Result := -2147483647-1;`

Конечно, мало кто сейчас пользует Delphi7 (я пользуюсь им только для бенчмарков).
Но если есть командный файл для сборки, то должно работать (или удалите командный файл).

**Comment by vtereshkov** [comment]
Спасибо! Сейчас исправлю. Это несколько неожиданно. Delphi 6 не жалуется (то ли не замечает, то ли корректнее отрабатывает). Наверное, проблема из-за того, что минус и число трактуются отдельно.
