### ISSUE TITLE
Automatic "uses" of referenced units?

### ISSUE THREAD

**Issue by tinyBigGAMES** [vtereshkov/xdpw#7]
Hi, great work on compiler since I last visited! 

What would need to be changed/added so you simply do this:

```
program test;
uses
  unit1, unit2;
begin
end.
```

`xdpw test.pas`

So that you can eliminate the need to have to specify the included units on the command line? If I can figure out how to get his working, I should be able to start using xdpw in my projects. All the basic features are there and you are updating on a regular basis, which is fantastic to see.

**Comment by vtereshkov** [comment]
I will try to do this in the near future.

**Comment by tinyBigGAMES** [comment]
Nice. Thanks!

**Comment by vtereshkov** [comment]
@tinyBigGAMES Please check the updates.

**Comment by tinyBigGAMES** [comment]
Whoa (rubbing hands together with great anticipation), fantastic! Many thinks my friend.

**Comment by tinyBigGAMES** [comment]
Oh, wonderful, you even have support for specifying a "units" folder path. NICE! Good work bro. Thanks!
