### ISSUE TITLE
The road to Unicode support?

### ISSUE THREAD

**Issue by tinyBigGAMES** [vtereshkov/xdpw#8]
Hi, it would be nice to have support for unicode strings. The library that I want to use with it (around 700+ exported routines at this point) expect unicode strings.

I did manage to make the changes so that it compiles under the most recent version of Delphi, which is unicode and which my game library is made with.

Maybe create a special "experimental" branch for things such as this and this way your standard branch can remain unaffected?

In any case, great the see the steady stream of progress being made. It has come a long way since I first discovered it.

**Comment by vtereshkov** [comment]
@tinyBigGAMES As a temporary solution, I can propose two separate data types, _WideChar_ and _WideString_. _WideChar_ will be internally represented as _Word_, and _WideString_ as _array [1..N] of Word_. That is, _WideString_ will be a static string 2 bytes wide and up to N-1 characters long, terminated by a null word. Here, N=256, or 512, or anything. If I'm not mistaken, this _WideString_, when passed to a function as a _const_ argument, will be equivalent to _LPWCSTR_ from WinAPI. These new types are only for interacting with your API, while all internal string representations will remain ANSI-compatible. Two functions, _AnsiToUnicode_ and _UnicodeToAnsi_, will also be provided.

The approaches I would like to avoid by any means are:

- Dynamic strings 
- Strings containing encoding metadata
- Variable-width encoding
- _Char_ = _WideChar_, _String_ = _WideString_

Will it be sufficient for you to start experimenting?

P.S. In the last commit I have removed the limits on the number of statically imported functions.

**Comment by tinyBigGAMES** [comment]
Yes, that sounds fantastic. Many thanks.

**Comment by vtereshkov** [comment]
@tinyBigGAMES But this WideString will be incompatible with Delphi's WideString or UnicodeString, since they both are not mere arrays of wide characters. Is that OK? I see that you are using UnicodeString in your GPL.DLL API. For example, in a disassembly listing of Buffer_LoadFromFile, I see that it tries to modify the argument's reference count. We will have no reference count in the first implementation of WideString.

So, if this is OK, could you please compile (with Delphi) a tiny DLL that exports just one or two STDCALL functions that take our WideString (i.e., a simplest kind of a Unicode string sufficient for you to start experimenting) and make something visible with it - for example, return its copy in the upper case, or print it to a file, or whatever you want? I will test my compiler with this DLL.

**Comment by tinyBigGAMES** [comment]
Ok, here ya go.

[test001.zip](https://github.com/vtereshkov/xdpw/files/4050126/test001.zip)

**Comment by vtereshkov** [comment]
@tinyBigGAMES Thank you!

**Comment by tinyBigGAMES** [comment]
sure, no problem.

Oh, note too that the code base need to be able to compile in later version of Delphi. I understand you said the internals will remain ansi and that is fine, but if you do not make it compliable from your end I have to make all those changes to the code to get it to compile in Delphi 2009+ and with each release from you I have to do it all over again. You understand my point.

**Comment by vtereshkov** [comment]
@tinyBigGAMES As for Unicode strings, please check the latest commit and the source files attached to this message. I have compiled them with XD Pascal and, as far as I can see, the EXE interacts properly with your DLL.

As for modifications needed to compile smoothly with Delphi 2009+, I can propose changing Char to TChar and PChar to PTChar throughout the compiler source (the type String has already been replaced with TString). These types will be defined in Common.pas. You will have to replace TChar = Char with TChar = AnsiChar etc. Is this sufficient for you?
[test001.zip](https://github.com/vtereshkov/xdpw/files/4051428/test001.zip)

**Comment by tinyBigGAMES** [comment]
Wonderful, thanks so much. 

Yes, that will be sufficient to make it work, which is what I do actually to make it work with Delphi 2009+

Thanks again.

**Comment by vtereshkov** [comment]
@tinyBigGAMES Please check the latest update.

**Comment by tinyBigGAMES** [comment]
Here are the changes I have to make in order for it to compile (also without warnings) in Delphi 2009+

see changes in: common.pas(38, 39, 40, 41, 82, 86), linker.pas(463) and xdpw.pas(82)

[xdpw_delphi2009plus.zip](https://github.com/vtereshkov/xdpw/files/4051793/xdpw_delphi2009plus.zip)

**Comment by vtereshkov** [comment]
@tinyBigGAMES Please check the update. Keep `TGenericString = string` as is.

**Comment by tinyBigGAMES** [comment]
In Delphi 2009+ string and char are unicode by default and a variant record can not have a managed string type. Char and string MUST be defined as AnsiChar and AnsiString so that Delphi 2009+ will compile them as ansi types. This is why I had to define them like I did in common.pas. Also can not have a managed string type in a variant record, is why I define it as ShortString.

**Comment by vtereshkov** [comment]
@tinyBigGAMES Yes, I understand this. The today's commit, as I hope, contains everything you need, including TShortString. Now all you have to do is changing four lines in Common.pas. Or I miss the point?

**Comment by tinyBigGAMES** [comment]
just tried it, YES! perfect, works. Thank you man!

**Comment by vtereshkov** [comment]
An updated version of test001 - now without the `name` semi-keyword, which is no longer needed.
[test001.zip](https://github.com/vtereshkov/xdpw/files/4136748/test001.zip)
